
# Constants for Description
ARG_ABS_COORD = 0
ARG_TIME = 1
ARG_OBJECT = 2
ARG_PLAYER = 3  
ARG_REL_COORD = 4
ARG_RANGE = 5
ARG_LIST = 6
ARG_STRING = 7

# Constants for Fail
FAIL_PROTOCOL = 0
FAIL_FRAME = 1
FAIL_PERM = 2
FAIL_TEMP = 3
FAIL_NOSUCH = 4

# Constants for Feature
FEATURE_SECURE_THIS = 1
FEATURE_SECURE_OTHER = 2
FEATURE_HTTP_THIS = 3
FEATURE_HTTP_OTHER = 4
FEATURE_KEEPALIVE = 5

FEATURE_ORDERED_PLAYER		= 65535
FEATURE_ORDERED_OBJECT		= 65536
FEATURE_ORDERED_ORDERDESC	= 65537
FEATURE_ORDERED_BOARD		= 65538
FEATURE_ORDERED_RESOURCE	= 65539
FEATURE_ORDERED_CATEGORY	= 65540
FEATURE_ORDERED_DESIGN		= 65541
FEATURE_ORDERED_COMPONENT	= 65542
FEATURE_ORDERED_PROPERTY	= 65543

